.npmrc, package-lock.json, package.json, test/acceptance/user.controller.acceptance.ts
Signed-off-by: virkt25 <taranveer@virk.cc>
=> test: update tests to work with latest versions

package-lock.json, src/models/index.ts, src/models/order.model.ts, src/models/shopping-cart-item.model.ts, src/models/shopping-cart.model.ts, src/repositories/shopping-cart.repository.ts
Fixes https://github.com/strongloop/loopback4-example-shopping/issues/15
=> chore: separate shopping cart item into its own file

public/index.html.template
Signed-off-by: virkt25 <taranveer@virk.cc>
Update the home page template.
=> fix: update template

index.js, package-lock.json, package.json, recommender.js, src/controllers/user-order.controller.ts, src/controllers/user.controller.ts, src/models/user.model.ts, src/repositories/user.repository.ts, test/acceptance/user-order.controller.acceptance.ts, test/acceptance/user.controller.acceptance.ts
=> chore: upgrade to LoopBack4@1.x

package-lock.json, src/controllers/user.controller.ts, src/utils/user.authentication.ts, test/acceptance/user.controller.acceptance.ts, test/unit/utils.authentication.unit.ts
connect to https://github.com/strongloop/loopback4-example-shopping/issues/35
Refactor the password hash into utility functions.
=> refactor: extract hash password

package.json
=> chore: add greenkeeper configuration

README.md
=> chore: add travis badge and move loopback logo to bottom

package-lock.json, src/controllers/specs/user-controller.specs.ts, src/controllers/user.controller.ts, src/repositories/user.repository.ts
Fix the input displayed in explorer of login function.
=> fix: add schema to describe credentials

packages/shopping/src/__tests__/acceptance/user.controller.acceptance.ts, packages/shopping/src/controllers/user.controller.ts, packages/shopping/src/services/jwt-service.ts
Remove unused dependency injections and replace string literal with
AuthenticationBindings.CURRENT_USER
Signed-off-by: Dominique Emond <dremond@ca.ibm.com>
=> refactor: remove unused injections and remove string literal

packages/shopping/src/__tests__/unit/utils.retry.unit.ts
See https://travis-ci.com/strongloop/loopback4-example-shopping/jobs/243828270
=> chore: relax tests to avoid CI failures

README.md, packages/shopping/src/__tests__/acceptance/shopping-cart.controller.acceptance.ts
issue: https://github.com/strongloop/loopback-next/issues/3695
=> docs: add documentation for authorization

packages/shopping/src/utils/security-spec.ts
refactor according to https://github.com/strongloop/loopback-next/issues/4461
=> refactor: rename security scheme name

README.md
There has been a number of questions on starting the app, and it seems like the `npm run docker:start` is not visible to users.  Restructure the content a bit so that it's clear to users what are the minimal steps to get the app up and running.
=> fix(loopback4-example-shopping): update docker start cmd

README.md
Replaced "Unprotected" with "Protected".
=> Replaced "Unprotected" with "Protected"

.vscode/launch.json
=> feat: add vscode mocha test launch config

packages/shopping/src/__tests__/fixtures/redis-mongo-docker.ts
Fix: naming conflict introduced with use of testcontainers
fixes #452
=> fix: resolve container conflict on test

packages/shopping/src/application.ts, packages/shopping/src/authentication-strategies/jwt-strategy.ts, packages/shopping/src/utils/security-spec.ts
utilise new binding method and include securityScheme
=> refactor: update auth strategy binding

packages/shopping/src/repositories/order.repository.ts, packages/shopping/src/repositories/product.repository.ts, packages/shopping/src/repositories/shopping-cart.repository.ts, packages/shopping/src/repositories/user-credentials.repository.ts, packages/shopping/src/repositories/user.repository.ts
Fixes https://github.com/strongloop/loopback4-example-shopping/issues/617
=> fix: update repository classes to use dataSource for constructor

packages/shopping/src/__tests__/acceptance/user-order.controller.acceptance.ts, packages/shopping/src/controllers/user-order.controller.ts
Changed params to object and implemented two filter tests from #17
=> feat: Add missing filter tests

packages/shopping/package.json, packages/shopping/src/application.ts
add placeholder author in package.json & remove temp workaround
=> feat: utilise new rest info oasEnhancer

packages/shopping/src/services/basic.authorizor.ts
Expanded comment to explain resolution of model ownership (also imports sorted by plugin).
Please check commit message is correct.
=> docs: explain authorization ownership resolution

packages/shopping/src/__tests__/acceptance/home-page.acceptance.ts, packages/shopping/src/sequence.ts
Fixes https://github.com/strongloop/loopback-next/issues/5650
=> fix: update sequence.ts to include invokeMiddleware

packages/shopping/src/services/user-service.ts
Guard against undefined email that would incorrectly return a user.
=> feat: add email check to verifyCredentials

bin/travis.sh
See https://travis-ci.com/github/strongloop/loopback4-example-shopping/jobs/358621703
=> chore: disable error check for the script

commitlint.config.js
=> chore: enforce Signed-off-by check for commits with DCO

packages/shopping/public/api.js, packages/shopping/public/templates.js, packages/shopping/public/ui.js, packages/shopping/src/__tests__/acceptance/user.controller.acceptance.ts, packages/shopping/src/controllers/specs/user-controller.specs.ts, packages/shopping/src/controllers/user.controller.ts
=> feat: add password reset functionality

CODEOWNERS
Welcome @mrmodise joining as a community maintainer in this repo! 🎉
=> chore: add mrmodise to codeowners

.renovaterc.json
Using https://github.com/strongloop/loopback.io/pull/1078 as the reference.
=> chore: enable renovate automerge

README.md
closes https://github.com/strongloop/loopback-next/issues/6704
Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>
=> chore: fix auth tutorial links

README.md, packages/shopping/src/__tests__/acceptance/user-management.controller.acceptance.ts, packages/shopping/src/application.ts
if definied, set JWT secret to value of env variable JWTSECRET
closes #925 
Signed-off-by: Johan Schon <johanschvn@gmail.com>
=> feat: allow using custom JWT secret token

packages/shopping/public/config.js
close #923
Signed-off-by: Johan Schon <johanschvn@gmail.com>
=> refactor: allow using any host and port on the frontend

README.md, openshift/Dockerfile.monorepo, openshift/Dockerfile.recommender, openshift/Dockerfile.shopping, openshift/README.md, openshift/base.yaml, openshift/recommender.yaml, openshift/shopping.yaml
How to build and deploy loopback4-example-shopping on OpenShift Container Platform
=> feat: include OpenShift container build and deploy steps

README.md
=> chore: update travis-ci badge to github-actions

packages/shopping/public/api.js, packages/shopping/public/config.js, packages/shopping/public/product-management.html, packages/shopping/public/product-management.js, packages/shopping/public/shoppy.js, packages/shopping/public/templates.js, packages/shopping/public/ui.js
Closes #440 
PR is missing product update that can be done separately. I couldn't finish it off due to tight schedule on other priorities. I included the scaffolding for it though
=> feat: create/list/delete operation on products 

README.md, kubernetes/README.md, openshift/README.md, openshift/base.yaml, package.json, packages/recommender/package.json, packages/shopping/package.json, packages/shopping/src/__tests__/acceptance/user-order.controller.acceptance.ts
As part of https://github.com/strongloop/loopback-next/issues/7595.
=> chore: move this repo to loopbackio org

.github/workflows/ci.yml
Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>
=> ci: update Node.js verisons
