loopbackio/loopback4-example-shopping

index.ts
package-lock.json
package.json
recommender.js
recommender/index.ts
recommender/mock-recommendation-app.ts
recommender/recommendations.json
src/application.ts
src/controllers/user.controller.ts
src/datasources/index.ts
src/datasources/recommender.datasource.json
src/datasources/recommender.datasource.ts
src/models/index.ts
src/models/product.model.ts
src/services/recommender.service.ts
test/acceptance/user.controller.acceptance.ts
tsconfig.json

fixes https://github.com/strongloop/loopback-next/issues/1482
---
implements a mock recommendation service -- runs on port 3001.
implements a proxy service to talk to the recommendation service. 
both services start by running `npm run start`.

feat: product recommendation 

---

package-lock.json

https://github.com/ahmadnassri/node-har-validator/issues/112#issuecomment-437378269
The version present in lockfile is unplublished. Updated it to now resolved with latest published version
This should resolve issue #25

fix: har-validator version resolution fixed

---

package-lock.json
src/authentication-strategies/JWT.strategy.ts
src/utils/user.authentication.ts
test/unit/utils.authentication.unit.ts

connect to https://github.com/strongloop/loopback-next/issues/1997
previous PR: https://github.com/strongloop/loopback4-example-shopping/pull/26
Refactor the decoding user code into a util function, so that it could be shared among different controllers other than REST.

refactor: extract decode user to util

---

src/utils/user.authentication.ts
test/acceptance/user.controller.acceptance.ts
test/unit/utils.authentication.unit.ts

Fix the accesstoken generation function by checking the password instead of sending the plain password.
A follow up PR for https://github.com/strongloop/loopback4-example-shopping/pull/26
And connect to the first acceptance criteria in https://github.com/strongloop/loopback4-example-shopping/issues/35

fix: hash the password

---

src/application.ts
src/controllers/user.controller.ts
src/keys.ts
src/services/JWT.authentication.service.ts
src/services/hash.password.bcryptjs.ts
test/acceptance/user.controller.acceptance.ts
test/unit/helper.ts
test/unit/utils.authentication.unit.ts

A follow up PR for https://github.com/strongloop/loopback4-example-shopping/pull/33
connect to https://github.com/strongloop/loopback4-example-shopping/issues/40
- Refactor bcrypt hashing related functions into a service.
- Decouple the password hashing service from JWT service.
Details see discussion in https://github.com/strongloop/loopback4-example-shopping/pull/33#discussion_r255927845

refactor: bcrypt hash

---

README.md

This is a follow-up for the recent migration of Travis CI builds from https://travis-ci.org to newer https://travis-ci.com. See https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

chore: update README to use badge from travis-ci.com (not org)

---

.travis.yml

We run the CI for pull requests, no need to run them again for branches.
At the moment, we run Travis CI twice for each PR, which slows down the process significantly.

ci: disable builds of Renovate branches

---

packages/shopping/src/sequence.ts

Rework the code handling authentication errors to correctly preserve stack trace of the original error, instead of creating a new error instance with a stack pointing to the Sequence class only.

fix: error handling in Sequence

---

CODEOWNERS

I'd like to remove myself from CODEOWNERS. I am already spending quite a lot of time in reviewing pull requests to loopback-next and would like somebody else to take ownership of this example repository.
This is a follow-up for https://github.com/strongloop/loopback4-example-shopping/pull/146

chore: remove bajtos from CODEOWNERS

---

.travis.yml

As discussed in https://github.com/strongloop/loopback-next/pull/3105: We don't have any platform specific code, I think it's enough to pick a single Node.js version to test on MacOS. We test different Node.js versions on Linux.

Add Node.js 12 for MacOS & Linux and remove Node.js 8 & 10 on MacOS on Travis 

---

README.md
packages/shopping/package-lock.json
packages/shopping/package.json
packages/shopping/src/application.ts
packages/shopping/src/models/order.model.ts
packages/shopping/src/models/shopping-cart.model.ts

Closes https://github.com/strongloop/loopback4-example-shopping/issues/69

Improve the code and add more details to the doc

---

packages/shopping/src/controllers/ping.controller.ts
packages/shopping/src/controllers/shopping-cart.controller.ts
packages/shopping/src/controllers/user-order.controller.ts
packages/shopping/src/controllers/user.controller.ts

1. Run `npm run docker:start && npm start; npm run docker:stop`
2. Run `npm install -g openapi-to-graphql`
3. Run `openapi-to-graphql --cors -p 3002 -f -u http://localhost:3000 http://localhost:3000/openapi.json`
```
OpenAPI-to-GraphQL creation event error:  Cannot use 'in' operator to search for '$ref' in number
(node:65318) UnhandledPromiseRejectionWarning: AssertionError: Schema object cannot have additionalProperty: patternProperties
at Assertion.fail (.../node_modules/should/as-function.js:275:17)
at Assertion.value (.../node_modules/should/as-function.js:356:19)
at checkSubSchema (.../node_modules/oas-validator/index.js:132:16)
at walkSchema (.../node_modules/oas-schema-walker/index.js:53:5)
at Object.walkSchema (.../node_modules/oas-schema-walker/index.js:82:13)
at checkSchema …
```

Fix openapi schema

---

packages/shopping/src/__tests__/acceptance/user.controller.acceptance.ts
packages/shopping/src/__tests__/unit/utils.authentication.unit.ts
packages/shopping/src/services/user-service.ts

The error message returned on a failed login attempt should always be the same regardless of whether
the email or the password is wrong. Since this is a showcase application, it should adhere to security best practices. As a reference see [OWASP recommendation](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#login).

refactor: change login error message

---

packages/shopping/src/services/jwt-service.ts

Correct naming from `decryptedToken` to `decodedToken`. The prior naming is misleading as it implies
that the token is encrypted instead of encoded.

refactor: correct misleading variable name

---

bin/travis.sh

The `mongodb` formulae is gone from brew.

build: fix travis script for CI to use mongodb-community formulae

---

packages/shopping/src/application.ts
packages/shopping/src/controllers/user.controller.ts
packages/shopping/src/utils/security-spec.ts

Make the authentication token dialog available in API Explorer
Connected to https://github.com/strongloop/loopback-next/issues/3740

feat: enable auth token dialog in api explorer

---

package-lock.json
packages/recommender/data/recommendations.json
packages/recommender/package-lock.json
packages/recommender/package.json
packages/recommender/protos/recommendation.proto
packages/recommender/src/__tests__/integration/recommender-grpc.integration.ts
packages/recommender/src/__tests__/integration/recommender-rest.integration.ts
packages/recommender/src/index.ts
packages/recommender/src/recommendation-grpc.ts
packages/recommender/src/recommendation-rest.ts
packages/shopping/package-lock.json
packages/shopping/package.json
packages/shopping/protos/recommendation.proto
packages/shopping/src/__tests__/acceptance/user.controller.acceptance.ts
packages/shopping/src/datasources/index.ts
packages/shopping/src/datasources/mongo.datasource.json
packages/shopping/src/datasources/recommender-grpc.datasource.json
packages/shopping/src/datasources/recommender-grpc.datasource.ts
packages/shopping/src/services/index.ts
packages/shopping/src/services/recommender-grpc.service.ts
packages/shopping/src/services/recommender-rest.service.ts
packages/shopping/src/services/recommender.service.ts

This is a spin-off from https://github.com/strongloop/loopback4-example-shopping/pull/268.
1. Allow recommender service to expose gRPC endpoints
2. Allow shopping to connect to recommender over gRPC and REST

feat: add grpc support for recommender service

---

README.md
packages/shopping/src/__tests__/acceptance/authentication.acceptance.ts
packages/shopping/src/__tests__/acceptance/authorization.acceptance.ts
packages/shopping/src/__tests__/acceptance/user-order.controller.acceptance.ts
packages/shopping/src/__tests__/acceptance/user.controller.acceptance.ts
packages/shopping/src/controllers/user.controller.ts
packages/shopping/src/models/index.ts
packages/shopping/src/models/user-credentials.model.ts
packages/shopping/src/models/user.model.ts
packages/shopping/src/repositories/index.ts
packages/shopping/src/repositories/user-credentials.repository.ts
packages/shopping/src/repositories/user.repository.ts
packages/shopping/src/services/user-service.ts
packages/shopping/src/services/validator.ts

Introduce `UserCredentials` models to hold hashed passwords, add has-one relation from `User` to `UserCredentials`.
Rework authentication-related code to work with the new domain model.
See https://github.com/strongloop/loopback-next/issues/1996 for additional information.
_I have to say the code in the example app is a bit messy. Some things are (unnecessarily) duplicated in multiple places, therefore my pull request had to touch quite few files to update all duplications. Considering our current priorities, I am leaving refactoring & cleanup out of scope of my PR._

feat: extract local credentials into a new model

---

.vscode/settings.json
packages/shopping/src/__tests__/acceptance/authentication.acceptance.ts
packages/shopping/src/__tests__/acceptance/authorization.acceptance.ts
packages/shopping/src/__tests__/acceptance/helper.ts
packages/shopping/src/application.ts

Before this PR, the `Shoppy` login fails as there are no pre-defined users/products populated.
@hacksparrow Do you have docs to describe that?

feat: enable migrateSchema so that users/products are populated with npm start

---

CODEOWNERS

Update Functional Area Owners based on the team discussion we had
elsewhere, see https://github.com/strongloop/loopback-next/pull/4559.

docs: update CODEOWNERS

---

.vscode/settings.json

Useful when Prettier off:
"typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": false;
Consistancy (from now on):
"editor.codeActionsOnSave": {
"source.organizeImports": true,
// ...
},

feat: .vscode add useful rules

---

tsconfig.json

This speeds up `npm run eslint`, good practice
see https://github.com/strongloop/loopback-next/pull/4707

chore: remove dist files from root tsconfig + update node_modules pattern

---

package.json

Reverts #45 as greenkeeper is not used anymore (replaced by renovate)

chore: remove greenkeeper configuration

---

packages/shopping/public/index.html

Since v4.loopback.io is no longer in use, remove any references for v4.loopback.io.

fix: remove ref for v4.loopback.io

---

.github/stale.yml

A follow-up for https://github.com/strongloop/loopback-next/pull/6745
/cc @strongloop/loopback-maintainers

chore: enable StaleBot using config from loopback-next

---

.travis.yml

The recent builds are building for OSX:
```
==> Installing gdal dependency: qt
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
softwareupdate --all --install --force
If that doesn't show you an update run:
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
Alternatively, manually download them from:
https://developer.apple.com/download/more/.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build …
```

chore: fix travis build

---

.github/workflows/ci.yml

Github action seems to be usinng Mongodb 4.4 thus installing latest version breaks pipeline. In this PR am pinning the version of Mongodb to 4.4.
Signed-off-by: mrmodise <modisemorebodi@gmail.com>

ci: pin mongodb version to 4.4 to avoid brew link error

---

package-lock.json
packages/shopping/package-lock.json
packages/shopping/package.json
packages/shopping/src/__tests__/acceptance/user-management.controller.acceptance.ts

Updates the package-lock.json files to help the `npm ci` command grabs the upgraded package versions.

chore: update dependency @loopback/rest to v10

---

.github/workflows/ci.yml

loopback-next modules only support Node.js 14+, so updating the GH actions to reflect what's needed. 

chore: update GH actions for Node.js version
